### PR TITLE
Fixed the bad object check issue

### PR DESCRIPTION
**Pull request by Shai1436**

### CODE REVIEW

**Comment by jeysal** [comment]
Thanks for the PR and adding tests, but I don't think this is the behavior you'd want? As I mentioned in #2, much like for React elements, I think ommiting `null` and `undefined` children completely in serialization would be the correct handling

**Comment by Shai1436** [comment]
Sorry for the late reply. I have omitted the `null` and `undefined` children. Please take a look.

**Comment by jeysal** [comment]
Hi, sorry, your solutions does not really omit `null` and `undefined` children but rather makes them like empty text nodes, which does not serialize the same. I've pushed https://github.com/jeysal/pretty-format-snabbdom/commit/f061ee73f6fd5098583c1a4ad02d886a4e0fd0d4 which should be the proper solution to your issue I think, and I will publish a new version.

**Comment by Shai1436** [comment]
Let me know when you publish the new version

**Comment by jeysal** [comment]
> Let me know when you publish the new version

1.0.1 should have already been published

**Comment by Shai1436** [comment]
Cool, thanks.

**Pull request closed without merging**
